### ISSUE TITLE
Failed to compile. Getting TypeError: Cannot read property '_init' of undefined

### ISSUE THREAD

**Issue by raminf** [FGRibreau/ui-predicate#6]
### Prerequisites
 - [x] I have read the [Contributing guidelines](https://github.com/fgribreau/ui-predicate/blob/master/.github/CONTRIBUTING.md)
 - [x] I have read the [Code of conduct](https://github.com/fgribreau/ui-predicate/blob/master/.github/CODE_OF_CONDUCT.md) and I agree with it

### Description
Followed the installation instructions under Vue.js 2:

In my main.js:

```
import Vue from 'vue'
import UIPredicate from 'ui-predicate-vue'
Vue.component(UIPredicate)
```
Getting compile error. Commenting out the above lines from the project makes it compile again. 

### Only for bugs :bug:
**Version :** 0.3.0

#### Expected behavior
Compile

#### Actual behavior
Compile error

#### How to reproduce
After adding the above lines, I get:

```
Failed to compile.

./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/ui-predicate-vue/src/ui-predicate-comparison.vue

Module build failed: TypeError: Cannot read property '_init' of undefined (While processing preset: "
[...]/node_modules/vue/dist/vue.runtime.common.js")
    at Vue ([...]/node_modules/vue/dist/vue.runtime.common.js:4727:8)

    at [...]/node_modules/babel-core/lib/transformation/file/options/option-manager.js:317:46
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets ([...]/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets ([...]/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions ([...]/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init ([...]/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions ([...]/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File ([...]/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform ([...]/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile ([...]/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports ([...]/node_modules/babel-loader/lib/index.js:173:20)
 @ ./node_modules/ui-predicate-vue/src/ui-predicate-comparison.vue 4:0-110 5:0-123
 @ ./node_modules/ui-predicate-vue/src/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

Have also tried importing individual components (UIPredicateOptions, UIPredicateComparison, UIPredicateComparisonArgument, UIPredicateCompound, UIPredicate) but keep ending with the same error.

Used yarn to install and have the following line in the package.json dependencies: 

`    "ui-predicate-vue": "^0.3.0"
`

**Comment by raminf** [comment]
**Update:** started with a clean slate:
```
% npm --version
5.5.1
% vue --version
2.9.3
```
Created a VueJS 2 webpack project using vue-cli:

```
% vue init webpack pred
% npm install
% npm run dev 
```

Standard Vue page came up. Things working fine.

Added ui-predicate-vue:

`% yarn add ui-predicate-vue`

Then manually merged the examples from the ui-predicate example into App.vue and main.js so the src directory looks like this:

```
% ls src
App.vue			DateArgument.vue	assets			main.js
ColorArgument.vue	TextArgument.vue	components		router
```
Did another install to make sure all the dependencies were brought down.

```
% npm install
% npm run dev
```

Got a 'stage-0' error message:

```
 error  in ./node_modules/ui-predicate-vue/src/ui-predicate.vue

Module build failed: Error: Couldn't find preset "stage-0" relative to directory "[...]/node_modules/ui-predicate-vue"

```

Googling indicated possible error with babel stage-0, so...

```
% npm install --save-dev babel-preset-stage-0
```

The another install and run:

```
% npm install
% npm run dev
```

Got the same error message as my first report:

```
 error  in ./node_modules/ui-predicate-vue/src/ui-predicate.vue

Module build failed: TypeError: Cannot read property '_init' of undefined (While processing preset: "[...]/pred/node_modules/vue/dist/vue.runtime.common.js")
    at Vue ([...]/pred/node_modules/vue/dist/vue.runtime.common.js:4727:8)
...
```

Trying to establish if it's some interaction with my existing project or not. Looks like it happens with a bare-bones vanilla project. 

Still learning my way around VueJS. Will keep exploring.

**Comment by FGRibreau** [comment]
@raminf thanks for the report :+1: 

I do not have much time for now, a team at @ouest-france will use this component in VueJS in approx. ~3 months and for the time being I'm waiting on their feedback concerning the integration of the ui-predicate Vue wrapper inside their project, but if you find the issue before and push a PR of course I will accept it :)

**Comment by raminf** [comment]
OK thanks for the heads-up. I've also moved attention to other things but really want to use it in my current project. Will go back and take a deeper look. By the time someone figures out what's going on VueJS 3 will likely be out and will change everything again :-) 

Thanks for the work and putting it out.

**Comment by FGRibreau** [comment]
@raminf just a heads-up, Ouest-France is currently implementing it and we fixed some issues, so you might want to give it another try :)

**Comment by raminf** [comment]
Thanks, tried it with the latest update. Still getting the same _init error. I also tried building the provided example as a clean standalone vue project and got the same error.

One tip... the example provided in ui-predicate-vue/getting-started does:

`import UIPredicateVue from '..';`

That '..' presumes only works if the code is inside the main project. You may want to try a clean standalone build without the dependency on the '..' path and see if you get the same issue.

Will dig a bit deeper and see if it's got something to do with my installation. 
Thanks again!
